# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 09:05
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default="./static/close.png", upload_to=b'whatever'),
            preserve_default=False,
        ),
    ]
